--- Insere dados na tabela produtos 
Insert into VersaoFinal.Produto (Nome, Descricao, Preco, CaminhoImagem, PalavrasChave)
Values 
-- Insere dados dos aperitivos
('Aipim Frito', 'Porção de aipim frito (400 gramas)', 18.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/aipim_frito.PNG?raw=true', 'aperitivos, batata frita, mandioca frita, polenta frita, acompanhamento'),
('Bata Frita', 'Porção de bata frita (400 gramas)', 18.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/batata_frita.PNG?raw=true', 'aperitivos, polenta frita, mandioca frita, ketchup, acompanhamento'),
('Sachê de Ketchup', 'Sachê de 9g de ketchup', 2.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/ketchup.PNG?raw=true', 'tempero, batata frita, polenta frita, maionese, acompanhamento'),
('Sachê de maionese', 'Sachê de 8g de maionese', 2.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/maionese.PNG?raw=true', 'tempero, batata frita, mandioca frita, ketchup, acompanhamento'),
('Sachê de mostarda','Sachê de 5g de mostarda',2.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/mostarda.PNG?raw=true','tempero, batata frita, mandioca frita, ketchup, acompanhamento'),
('Onion rings', 'Porção de cebola à milanesa (300 gramas)', 25.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/onion_rings.PNG?raw=true','aperitivos, batata frita, mandioca frita, aipim frito, acompanhamento'),
('Polenta frita', 'Porção de polenta frita (400 gramas)', 18.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/aperitivos/polenta_frita.PNG?raw=true', 'aperitivos, batata frita, mandioca frita, aipim frito, acompanhamento'),
-- Insere dados das bebidas 
('Água com gás', 'Garrafa de água com gás (500 ml)', 5.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/agua_com_gas.PNG?raw=true','Água sem gás, refrigerante, sachê de ketchup, sachê de maionese, acompanhamento'),
('Água sem gás', 'Garrafa de água sem gás (500 ml)', 5.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/agua_sem_gas.PNG?raw=true','Água com gás, Refrigerante, Sachê de ketchup, Sachê de maionese, Acompanhamento'),
('Coca-Cola (2l)', 'Garrafa de refrigerante Coca-Cola (2l)', 10.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/coca_2litros.PNG?raw=true', 'Água com gás, Refrigerante, Fanta, Coca-cola lata, Guaraná 2l'),
('Coca-cola lata (350ml)', 'Lata de refrigerante Coca-cola (350 ml)', 6.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/coca_lata.PNG?raw=true', 'Água com gás, Refrigerante, Fanta, Coca-cola 2l, Guaraná 2l'),
('Coca-cola lata diet(350ml)', 'Lata de refrigerante Coca-cola diet (350 ml)', 6.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/coca_lata_diet.PNG?raw=true','Água com gás, Refrigerante, Fanta, Coca-cola 2l diet, Guaraná 2l'),
('Fanta Laranja (350ml)', 'Lata de refrigerante Fanta Laranja (350 ml)', 6.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/fanta_lata.PNG?raw=true', 'Água com gás, Refrigerante, Guaraná lata, Fanta Uva, Guaraná 2l'),
('Fanta Uva (350ml)', 'Lata de refrigerante Fanta Uva (350 ml)', 6.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/fanta_uva.PNG?raw=true','Água com gás, Refrigerante, Guaraná lata, Fanta Laranja, Guaraná 2l'),
('Guaraná Antártica (2l)','Garrafa de refrigerante Guaraná Antártica (2l)', 10.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/guarana_2l.PNG?raw=true', 'Água com gás, Refrigerante, Guaraná lata, Coca-Cola 2l, Guaraná 2l diet'),
('Guaraná Antática diet (2l)', 'Garrafa de refrigerenta Guaraná Antártica diet (2l)', 10.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/guarana_2l_diet.PNG?raw=true','Água com gás, Refrigerante, Guaraná lata, Coca-cola 2l diet, Coca-cola 2l diet'),
('Guaraná Antártica lata (350ml)', 'Lata de refrigerante Guaraná Antártica (350ml)', 6.00 , 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/bebidas/guarana_lata.PNG?raw=true', 'Água com gás, Refrigerante, Coca-cola lata, Fanta Uva, Guaraná 2l'),
--Insere dados sobre lanches 
('Cachorro-quente', 'Cachorro-quente com uma salsicha, molho e batata-palha', 16.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/cachorro_quente_normal.PNG?raw=true', 'Cachorro-quente prensado, Xis-Salada, Coca-cola lata, Sachê de ketchup, batata frita'),
('Cachorro-quente prensado', 'Cachorro-quente prensado com duas salsichas, molho e batata-palha', 22.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/cachorro_quente_prensado.PNG?raw=true', 'Cachorro-quente, Xis-Bacon, Coca-cola lata, Sachê de ketchup, batata frita'),
('Hambúrguer com bacon', 'Hambúrguer 180g, cebola caramelizada e mussarela', 38.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/hamburguer_bacon.PNG?raw=true', 'Xis-Bacon, Batata frita, Coca-cola lata, Sachê de ketchup, Sachê de maionese'),
('Hambúrguer com calabresa', 'Hambúrguer 180g, calabresa, queijo e molho', 32.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/hamburguer_calabresa.PNG?raw=true', 'Xis-Calabresa, Hambúrguer com bacon, Coca-cola lata, polenta frita, Sachê de ketchup'),
('Hambúrguer com frango', 'Hambúrguer de frango, salada e queijo', 30.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/hamburguer_frango.PNG?raw=true', 'Xis-Frango, Hambúrguer com bacon, Hambúrguer com calabresa, polenta frita, Sachê de ketchup'),
('Hambúrguer simples', 'Hambúrguer bovino 180g, salada e queijo', 28.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/hamburguer_salada.PNG?raw=true', 'Xis-Salada, Hambúrguer com bacon, Hambúrguer com frango, batata frita, Sachê de ketchup'),
('Hambúrguer vegano', 'Hambúrguer de lentilha, salada e molho branco', 28.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/hamburguer_vegano.PNG?raw=true', 'Batata frita, polenta frita, Coca-cola lata, Sachê de ketchup, Sachê de maionese'),
('Xis-Bacon', 'Pão, Bife de Hambúrguer, queijo, ovo, batata palha e Bacon', 32.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/xis_bacon.PNG?raw=true', 'Hambúrguer com bacon, Xis-calabresa, Batata frita, Coca-cola lata, Sachê de ketchup'),
('Xis-Calabresa', 'Pão, calabresa, ervilha, milho e ovo',28.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/xis_calabresa.PNG?raw=true', 'Hambúrguer com calabresa, Xis-Bacon, Batata frita, Coca-cola lata, Sachê de ketchup'),
('Xis-Coração', 'Pão, coração de frango, queijo, ovo, milho e ervilha', 26.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/xis_coracao.PNG?raw=true', 'Xis-Salada, Xis-Bacon, Xis-calabresa, Batata frita, Coca-cola lata'),
('Xis-Frango', 'Pão, frango em cubos, queijo, milho e ervilha', 26.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/xis_frango.PNG?raw=true', 'Hambúrguer com frango, Xis-Salada, Xis-Bacon, Batata frita, Coca-cola lata'),
('Xis-Salada', 'Pão, bife de Hambúrguer, queijo, presunto, milho, tomate e ervilha', 28.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/xis_salada.PNG?raw=true', 'Hambúrguer simples, Xis-Frango, Batata frita, polenta frita, Coca-cola lata'),
('Hambúrguer duplo', 'Dois Hambúrguer de 180g, queijo, pepino e cebola', 42.00, 'https://github.com/vinimariano/senacProjetoIntegrador/blob/main/Banco-de-Dados/lanches/hamburguer_duplo.PNG?raw=true', 'Hambúrguer simples, Hambúrguer com bacon, Hambúrguer com calabresa,  Batata frita, Coca-cola lata');